### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by MH-Sameti** [Srijith-rkr/KAUST-Whisper-Adapter#2]
Hi, 
Can I ask how to use the pre-training model? Are the trained parameters accessible?
Thanks.

**Comment by Srijith-rkr** [comment]
Hey, I did not notice that you reopened the issue. Sorry for replying late. 

The function ( whisper.load_model() ) will automatically download the pretrained weights if you do not have them stored in the cache already.
