### ISSUE TITLE
Trying to Understand the similarity between this and Hugging face peft traning ?

### ISSUE THREAD

**Issue by Jeevi10** [Srijith-rkr/KAUST-Whisper-Adapter#3]

**Comment by Srijith-rkr** [comment]
This work uses a autoencoder based adapter mechanism as explained in the paper. I am not sure if HuggingFace also has the same. I know that HuggingFace uses a LoRA based adapter mechanism, which is better since it does not add to inference time latency after merging the adapter modules.
