### ISSUE TITLE
Trying to Understand the similarity between this and Hugging face peft traning 

### ISSUE THREAD

**Issue by Jeevi10** [Srijith-rkr/KAUST-Whisper-Adapter#4]
Is both hugging face transformer PEFT and your implementations are the same or is it different?

**Comment by Srijith-rkr** [comment]
As I mentioned in #3 we use the basic autoencoder based adapter mechanism and I think HuggingFace has LoRA adapters by default. They might have an audoencoder based implementation also, I am not sure. 

Our pipeline also has a token mapping mechanism on top of the output layer to map to the Arabic dialects. (You can also easily alter HuggingFace's Whisper code to achieve the same.)
